FROM mfocchi/trento_lab_framework:locosim

USER root
ENV DEBIAN_FRONTEND=noninteractive

# -----------------------------
# Quadrupeds stuff
# -----------------------------


RUN apt-get update && apt-get install -y \ 
	ros-noetic-imu-tools 


RUN python3 -m pip install --upgrade pip setuptools wheel
RUN python3 -m pip install --ignore-installed PyYAML
RUN python3 -m pip install --no-cache-dir -f https://storage.googleapis.com/jax-releases/jax_releases.html 'jax[cpu]'
RUN python3 -m pip install --no-cache-dir optax==0.1.4
RUN python3 -m pip install --no-cache-dir onnxruntime
RUN python3 -m pip install --no-cache-dir torch==2.0.0 --timeout=1000
RUN python3 -m pip install --no-cache-dir flax

RUN pip3 install line_profiler


# DO NOT redefine ENTRYPOINT or CMD
# They will automatically be inherited from mother-image

