FROM mfocchi/trento_lab_framework:locosim

USER root
ENV DEBIAN_FRONTEND=noninteractive

# -----------------------------
# Quadrupeds stuff
# -----------------------------


#climbing robot stuff
RUN pip3 install --no-cache-dir \  
     meshio casadi
	

# DO NOT redefine ENTRYPOINT or CMD
# They will automatically be inherited from mother-image

